### ISSUE TITLE
globby error

### ISSUE THREAD

**Issue by ddamato** [mohitsinghs/njk#16]
I really wish this package would work like it claims to.

Here's the command line I'm trying to run 
```sh
njk ./content -t ./templates -o _site/
```

I have `.md` files in `./content`, `.njk` templates in `./templates` and expecting everything to bundle up nicely in `_site/`. Instead, `globby` throws an error.

```sh
throw new TypeError('Patterns must be a string or an array of strings');
```

It looks like your package uses `globby.sync` twice, the first one seems to have the `['./content']` argument I'm passing but the second time around assigning `-t ./templates` just sends in `undefined`. I can see my `process.argv` is passing in all the arguments that I'm sending. Looks like your `commander` losing them.

**Comment by mohitsinghs** [comment]
Sorry, I was away from this package for a while. Upgrading commander broke this. Fixed in v3.4.9 🎉

**Comment by schwartzman** [comment]
Still broken.

**Comment by mohitsinghs** [comment]
@schwartzman can you provide more details ?

**Comment by schwartzman** [comment]
It throws the same error as in the initial report, with lots of mentions of globby in the trace. (Sorry I can't say much more than that, have already uninstalled and moved on to another tool.)

**Comment by mohitsinghs** [comment]
Oh, thanks anyways.
