### ISSUE TITLE
thank you for service

### ISSUE THREAD

**Issue by prmichaelsen** [mohitsinghs/njk#21]
sad to hear njk is no longer receiving lts. i enjoyed it while it lasted. may i ask what alternatives you are using?

**Comment by mohitsinghs** [comment]
Glad to hear that it helped. As of now, I'm using nextjs with some custom scripts to allow markdoc/markdown with it.

It's been more than an year since I stopped using it but I still maintain it. I am working on a port of njk to rust because I already miss it's simplicity.
