### ISSUE TITLE
Output directory

### ISSUE THREAD

**Issue by mdmoreau** [mohitsinghs/njk#7]
When using ```njk src/html/*.html --out dist``` files are being created in ```dist/src/html``` instead of directly to ```dist```. So, for example ```src/html/index.html``` gets output to ```dist/src/html/index.html```.

Is it possible to get the output to be ```dist/index.html``` instead of including the extra source folders? Thanks for the great CLI tool!

**Comment by mohitsinghs** [comment]
@mdmoreau Thanks for Reporting. You are right, glob files should have their parent directories as root by default. In previous versions, the current directory was treated as root for these files. I just released v3.0.5 and it should be fixed now. 🎉

**Comment by mohitsinghs** [comment]
@mdmoreau Please let me know if v3.0.5 fixed it for you or not.

**Comment by mdmoreau** [comment]
@mohitsinghs Looks to be working perfectly in my limited testing. Thanks for the quick fix!

I ran into a couple other issues while initially trying things out, but was able to sort them after looking through the code. Would you be interested in other issues that could improve compatibility with other systems (primarily Windows) and help things match up better with standard Nunjucks options?

**Comment by mohitsinghs** [comment]
Absolutely. We will work on those issues as well. I use njk on mac and linux, so that might be the reason I have not faced them yet.

**Comment by mdmoreau** [comment]
Sounds good - I'll create separate issues for anything else I run across.
