### ISSUE TITLE
Support quoting file globs

### ISSUE THREAD

**Issue by mdmoreau** [mohitsinghs/njk#8]
When using either of the following npm scripts, nothing gets built:

```"njk 'src/html/*.html'"```
```"njk \"src/html/*.html\""```

A number of CLI tools (ex. https://eslint.org/docs/user-guide/command-line-interface) recommend double quoting globs (which are escaped in the second example above) to ensure proper Windows support.

**Comment by mohitsinghs** [comment]
Okay, glob patterns should be handled correctly now. Thank you so much.
Please let me know if it still doesn't works.

**Comment by mdmoreau** [comment]
Looks good - thanks!
