### ISSUE TITLE
Consider renaming CLI options to match Nunjucks

### ISSUE THREAD

**Issue by mdmoreau** [mohitsinghs/njk#9]
One small point of confusion I had while migrating over from a different Nunjucks tool was the --template CLI option. After looking through the source, I realized that it seems to work the same as searchPaths (https://mozilla.github.io/nunjucks/api.html#filesystemloader).

You might consider renaming that to match or adding a note to help avoid similar confusion in the future.

**Comment by mohitsinghs** [comment]
Since, changing the option will be a breaking change, I've added clarification in the cli help. I hope it helps.
v3.0.6 is out now 🎉, and it was 99th commit in this repo 😜.

**Comment by mdmoreau** [comment]
Thanks!
